"""empty message

Revision ID: 93ecc424d205
Revises: 8200bf755cbf
Create Date: 2024-10-18 13:01:52.628583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93ecc424d205'
down_revision = '8200bf755cbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manager', schema=None) as batch_op:
        batch_op.drop_constraint('manager_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_constraint('tenant_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tenant_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('manager', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('manager_user_id_fkey', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
